openapi: 3.0.1
info:
  title: Instant Messaging API
  description: |
    API REST pour une messagerie instantanée qui comprend la gestion  des utilisateur·rice·s, des conversations et des messages. Cette API est utilisée dans  le cadre des modules 194, 195, 322, et 426 à l'EPAI Fribourg.
  contact:
    name: Jérôme Frossard
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080/api/v1
  description: Generated server url
security:
- BearerAuth: []
tags:
- name: user
  description: Gestion des utilisateurs
- name: token
  description: Gestion de l'authentification
- name: conversation
  description: Gestion des conversations
- name: participant
  description: Gestion des participants
- name: message
  description: Gestion des messages
paths:
  /users:
    get:
      tags:
      - user
      summary: Récupère la liste des utilisateur·rice·s
      description: Récupère la liste des utilisateur·rice·s avec pagination.
      operationId: get-users
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Liste récupérée avec succès
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/UsersResponseDto"
              example:
                _embedded:
                  users:
                  - id: 1
                    username: admin@example.com
                    displayName: Administrator
                    _links:
                      self:
                        href: /api/v1/users/1
                  - id: 11
                    username: sheana@example.com
                    displayName: sheana
                    _links:
                      self:
                        href: /api/v1/users/11
                _links:
                  self:
                    href: /api/v1/users?page=0&size=100
                page:
                  size: 20
                  totalElements: 2
                  totalPages: 1
                  number: 0
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    post:
      tags:
      - user
      summary: Crée un compte d'utilisateur·rice.
      description: "Crée un compte avec un nom d'utilisateur·rice et un mot de passe.\
        \ Le nom peut être soit une adresse e-mail, soit un numéro de téléphone au\
        \ format E.164."
      operationId: create-users
      requestBody:
        description: Utilisateur·rice à créer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateDto"
            example:
              username: hari@example.com
              displayName: Hari
              password: epai321
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "201":
          description: Utilisateur·rice créé
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/UserResponseDto"
              example:
                id: 11
                username: sheana@example.com
                displayName: sheana
                _links:
                  self:
                    href: /api/v1/users/11
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
  /tokens:
    post:
      tags:
      - token
      summary: Crée un token d'authentification (connexion)
      description: Renvoie un token d'authentification si le nom d'utilsateur et le
        mot de passe sont valides.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialDto"
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "201":
          description: Le jeton a été créer avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
  /conversations:
    get:
      tags:
      - conversation
      summary: Récupère les conversations de l'utilisateur·rice.
      description: Récupère les conversations dans lesquelles l'utilisateur·rice connecté·e
        est actif·ve.
      operationId: get-conversations
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "415":
          description: Unsupported Media Type
        "200":
          description: Liste de conversations récupérée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ConversationsReponseDto"
              example:
                _embedded:
                  conversations:
                  - id: 100
                    group: false
                    _embedded:
                      participants:
                      - userId: 11
                        username: sheana@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/100/participants/11
                      - userId: 12
                        username: idaho@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/100/participants/12
                    _links:
                      self:
                        href: /api/v1/conversations/100
                      participants:
                        href: /api/v1/conversations/100/participants
                _links:
                  self:
                    href: /api/v1/conversations?page=0&size=20
                page:
                  size: 20
                  totalElements: 1
                  totalPages: 1
                  number: 0
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    post:
      tags:
      - conversation
      summary: Crée une nouvelle conversation.
      description: "Crée une nouvelle conversation avec un ou plusieurs participant·\
        e·s. Le nom d'utilisateur peut être soit une adresse e-mail, soit un numé\
        ro de téléphone au format E.164."
      operationId: create-conversation
      requestBody:
        description: Utilisateur·rice à créer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConversationCreateDto"
            examples:
              Nouvelle conversation privée (username):
                description: Nouvelle conversation privée (username)
                value:
                  username: siona@example.com
              Nouvelle conversation de groupe (tableau de participants):
                description: Nouvelle conversation de groupe (tableau de participants)
                value:
                  participants:
                  - username: siona@example.com
                  - userId: 15
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "201":
          description: Conversation a été créée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ConversationResponseDto"
              examples:
                Conversation privée:
                  description: Conversation privée
                  value:
                    id: 1003
                    group: false
                    _embedded:
                      participants:
                      - userId: 13
                        username: siona@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/1003/participants/13
                      - userId: 11
                        username: sheana@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/1003/participants/11
                    _links:
                      self:
                        href: /api/v1/conversations/1003
                      participants:
                        href: /api/v1/conversations/1003/participants
                Conversation de groupe:
                  description: Conversation de groupe
                  value:
                    id: 1003
                    group: true
                    _embedded:
                      participants:
                      - userId: 13
                        username: siona@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/1003/participants/13
                      - userId: 15
                        username: fallom@example.com
                        role: MEMBER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/1003/participants/15
                      - userId: 11
                        username: sheana@example.com
                        role: OWNER
                        status: ACTIVE
                        _links:
                          self:
                            href: /api/v1/conversations/1003/participants/11
                    _links:
                      self:
                        href: /api/v1/conversations/1003
                      participants:
                        href: /api/v1/conversations/1003/participants
        "500":
          description: Internal Server Error
  /conversation/{conversationId}/messages:
    get:
      tags:
      - message
      summary: Récupère les messages d'une conversation
      description: Récupère les messages d'une conversation donnée. L'utilisateur·rice
        connecté·e doit être membre de la conversation.
      operationId: get-messages
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "415":
          description: Unsupported Media Type
        "200":
          description: Liste de messages récupérée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ConversationsReponseDto"
              example:
                _embedded:
                  messages:
                  - id: 100
                    senderId: 11
                    body: Hi Idaho!
                    participantStatus:
                    - userId: 11
                      readAt: null
                      deleted: false
                    - userId: 12
                      readAt: null
                      deleted: false
                    sentAt: 2025-05-07T13:48:31
                    _links:
                      self:
                        href: /api/v1/conversation/100/messages/100
                  - id: 101
                    senderId: 12
                    body: "Hey Sheana, good to hear from you."
                    participantStatus:
                    - userId: 11
                      readAt: null
                      deleted: false
                    - userId: 12
                      readAt: null
                      deleted: false
                    sentAt: 2025-05-07T13:48:31
                    _links:
                      self:
                        href: /api/v1/conversation/100/messages/101
                _links:
                  self:
                    href: /api/v1/conversation/100/messages?page=0&size=20
                page:
                  size: 20
                  totalElements: 2
                  totalPages: 1
                  number: 0
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    post:
      tags:
      - message
      summary: Ajoute un message à la conversation
      description: Ajoute un message à la conversation à partir de son identifiant.
      operationId: create-message
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageCreateDto"
            example:
              message: Salut! Quoi de neuf?
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Rôle ou statut de lea participant·modifié avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ParticipantResponseDto"
              example:
                userId: 15
                username: fallom@example.com
                role: MEMBER
                status: INACTIVE
                _links:
                  self:
                    href: http://localhost:8080/api/v1/conversation/110/participants/15
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
        "201":
          description: Created
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/MessageResponseDto"
  /users/{userId}:
    get:
      tags:
      - user
      summary: Récupère les informations d’un·e utilisateur·rice.
      description: Récupère les informations d'un·e utilisateur·rice à partir de son
        identifiant.
      operationId: get-user
      parameters:
      - name: userId
        in: path
        description: Identifiant de l'utilisateur·rice
        required: true
        schema:
          type: integer
          format: int64
        example: 11
      responses:
        "404":
          description: Utilisateur·rice non trouvé·e
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Utilisateur·rice récupéré avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/UserResponseDto"
              example:
                id: 11
                username: sheana@example.com
                displayName: sheana
                _links:
                  self:
                    href: /api/v1/users/11
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    delete:
      tags:
      - user
      summary: Supprime un·e utilisateur·rice.
      description: Supprime un·e utilisateur·rice à partir de son identifiant. Cette
        opération est irréversible et entraîne l’anonymisation de tous les messages
        envoyés par cette personne.
      operationId: delete-user
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Utilisateur·rice non trouvé·e
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "204":
          description: Utilisateur·rice supprimé avec succès.
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    patch:
      tags:
      - user
      summary: Modifie les informations d'un·e utilisateur·rice.
      description: Modifie les informations d'un·e utilisateur·rice à partir de son
        identifiant.
      operationId: update-user
      parameters:
      - name: userId
        in: path
        description: Identifiant de l'utilisateur·rice
        required: true
        schema:
          type: integer
          format: int64
        example: 11
      requestBody:
        description: Utilisateur·rice à créer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUpdateDto"
            examples:
              Modifier le mot de passe:
                description: Modifier le mot de passe
                value:
                  password: Epai123
              Modifier le nom d'utilisateur·rice:
                description: Modifier le nom d'utilisateur·rice
                value:
                  username: "+41799999123"
              Modifier le nom affichable:
                description: Modifier le nom affichable
                value:
                  displayName: Sheana
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "415":
          description: Unsupported Media Type
        "200":
          description: Données modifiées avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/UserResponseDto"
              example:
                id: 11
                username: sheana@example.com
                displayName: sheana
                _links:
                  self:
                    href: /api/v1/users/11
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
  /conversation/{conversationId}/participants/{participantId}:
    patch:
      tags:
      - participant
      summary: Modifie le rôle ou le statut d'un·e participant·e.
      description: |
        Modifie le rôle ou le statut d'un·e participant·e à partir de son identifiant.

        * Si la conversation est une conversation de groupe, le ou la propriétaire de la conversation peut bloquer un·e participant·e non propriétaire ou lui attribuer le rôle de propriétaire.

        * Si la conversation est une conversation privée, un·e participant·e peut changer son propre status d'actif à inactif. Cette opération est irréversible.
      operationId: update-participant
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      - name: participantId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 11
      requestBody:
        description: Utilisateur·rice à créer
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantUpdateDto"
            examples:
              Bloquer un utilisateur:
                description: Bloquer un utilisateur
                value:
                  status: BLOCKED
              Modifier le nom d'utilisateur·rice:
                description: Modifier le nom d'utilisateur·rice
                value:
                  username: "+41799999123"
              Modifier le nom affichable:
                description: Modifier le nom affichable
                value:
                  displayName: Sheana
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Rôle ou statut de lea participant·modifié avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ParticipantResponseDto"
              example:
                userId: 15
                username: fallom@example.com
                role: MEMBER
                status: INACTIVE
                _links:
                  self:
                    href: http://localhost:8080/api/v1/conversation/110/participants/15
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
  /conversation/{conversationId}/messages/{messageId}:
    patch:
      tags:
      - message
      summary: Modifie le statut du message pour un participant
      description: |
        Modifie le statut d’un message pour l’utilisateur·rice connecté·e.

        * Pour marquer le message comme lu, le champ `read` est mis à true. Si le message a déjà été lu, l'opération n'a pas d'effet.

        * Pour marquer le message comme supprimé, le champ `deleted` est mis à `true`. Cette opération est irréversible et entraîne la suppression logique du message pour cette personne.
      operationId: update-messages-status
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      - name: messageId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MessageUpdateDto"
            examples:
              Marquer le message comme lu.:
                description: Marquer le message comme lu.
                value:
                  read: true
              Marquer le message comme supprimer.:
                description: Marquer le message comme supprimer.
                value:
                  delete: true
        required: true
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Statut·modifié avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ParticipantResponseDto"
              example:
                id: 100
                senderId: 11
                body: Hi Idaho!
                participantStatus:
                - userId: 11
                  readAt: 2025-05-07T20:55:17
                  deleted: false
                - userId: 12
                  readAt: null
                  deleted: false
                sentAt: 2025-05-07T20:08:12
                _links:
                  self:
                    href: /api/v1/conversation/100/messages/100
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
  /conversations/{conversationId}:
    get:
      tags:
      - conversation
      summary: Récupère les détails d'une conversation.
      description: Récupère les détails d'une conversation à partir de son identifiant.
      operationId: get-conversation
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 100
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Détails de la conversation récupérée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ConversationResponseDto"
              example:
                id: 100
                group: false
                _embedded:
                  participants:
                  - userId: 11
                    username: sheana@example.com
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/api/v1/conversation/100/participants/11
                  - userId: 12
                    username: idaho@example.com
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/api/v1/conversation/100/participants/12
                _links:
                  self:
                    href: http://localhost:8080/api/v1/conversations/100
                  participants:
                    href: http://localhost:8080/api/v1/conversation/100/participants
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
  /conversation/{conversationId}/participants:
    get:
      tags:
      - participant
      summary: Récupèrer la liste des participant·e·s d'une conversation.
      description: Récupère la liste des participant·e·s d'une conversation à partir
        de son identifiant.
      operationId: get-participants
      parameters:
      - name: conversationId
        in: path
        description: Identifiant de la conversation
        required: true
        schema:
          type: integer
          format: int64
        example: 110
      responses:
        "429":
          description: Too Many Requests
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "200":
          description: Liste de participants récupérée avec succès.
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/ParticipantResponseDto"
              example:
                _embedded:
                  participants:
                  - userId: 11
                    username: sheana@example.com
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/api/v1/conversation/100/participants/11
                  - userId: 12
                    username: idaho@example.com
                    role: MEMBER
                    status: ACTIVE
                    _links:
                      self:
                        href: http://localhost:8080/api/v1/conversation/100/participants/12
                _links:
                  self:
                    href: http://localhost:8080/api/v1/conversation/100/participants
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
  /tokens/me:
    delete:
      tags:
      - token
      summary: Supprime le token de l'utilisateur·rice connecté·e (déconnexion).
      description: "Supprime le token de l'utilisateur·rice connecté·e (déconnexion).\
        \ Si le token est invalide ou expiré, la requête ne produit pas d'effet."
      operationId: login_1
      responses:
        "204":
          description: Token supprimé avec succès.
        "429":
          description: Too Many Requests
        "415":
          description: Unsupported Media Type
        "406":
          description: Not Acceptable
        "500":
          description: Internal Server Error
components:
  schemas:
    UserCreateDto:
      type: object
      properties:
        username:
          type: string
        displayName:
          type: string
        password:
          type: string
    Links:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Link"
    UserResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        displayName:
          type: string
        _links:
          $ref: "#/components/schemas/Links"
    CredentialDto:
      type: object
      properties:
        username:
          type: string
          description: Nom d'utilisateur·rice
          example: sheana@example.com
        password:
          type: string
          description: Mot de passe
          example: epai321
    TokenDto:
      type: object
      properties:
        token:
          type: string
          description: Token d'authentification
          example: 865b1cb2-bd0e-4468-8370-a8ae9ae4bd11t
    ConversationCreateDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
        participants:
          type: array
          items:
            $ref: "#/components/schemas/ParticipantDto"
    ParticipantDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
        role:
          type: string
        status:
          type: string
    ConversationResponseDto:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            participants:
              type: array
              items:
                $ref: "#/components/schemas/ParticipantResponseDto"
        _links:
          $ref: "#/components/schemas/Links"
        id:
          type: integer
          format: int64
        group:
          type: boolean
    ParticipantResponseDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
        role:
          type: string
        status:
          type: string
        _links:
          $ref: "#/components/schemas/Links"
    MessageCreateDto:
      type: object
      properties:
        message:
          type: string
    MessageResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        senderId:
          type: integer
          format: int64
        body:
          type: string
        sentAt:
          type: string
          format: date-time
        participantStatus:
          type: array
          items:
            $ref: "#/components/schemas/MessageStatusDto"
        _links:
          $ref: "#/components/schemas/Links"
    MessageStatusDto:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        readAt:
          type: string
          format: date-time
        deleted:
          type: boolean
    UserUpdateDto:
      type: object
      properties:
        username:
          type: string
        displayName:
          type: string
        password:
          type: string
    ParticipantUpdateDto:
      type: object
      properties:
        role:
          type: string
          enum:
          - OWNER
          - MEMBER
        status:
          type: string
          enum:
          - ACTIVE
          - INACTIVE
          - BLOCKED
    MessageUpdateDto:
      type: object
      properties:
        read:
          type: boolean
        delete:
          type: boolean
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    UsersResponseDto:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            users:
              type: array
              items:
                $ref: "#/components/schemas/UserResponseDto"
        _links:
          $ref: "#/components/schemas/Links"
        page:
          $ref: "#/components/schemas/PageMetadata"
    ConversationsReponseDto:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            conversations:
              type: array
              items:
                $ref: "#/components/schemas/ConversationResponseDto"
        _links:
          $ref: "#/components/schemas/Links"
        page:
          $ref: "#/components/schemas/PageMetadata"
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
